// Code generated by hashicorp/terraform-plugin-codegen-kubernetes; DO NOT EDIT
//
// This file contains the list of constructors for resources that have been autogenerated.
//
// This code was written by a robot on Jun 13, 2024 12:51:10 UTC.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/hashicorp/terraform-provider-kubernetes/internal/framework/provider/appsv1"
	"github.com/hashicorp/terraform-provider-kubernetes/internal/framework/provider/corev1"
)

var generatedResources = []func() resource.Resource{
	appsv1.NewDeployment,
	appsv1.NewStatefulSet,
	corev1.NewNamespace,
}
