name: Deferred Actions

on:
  pull_request:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
      - 'kubernetes/**/*.go'
      - "go.mod"
  workflow_dispatch:
    inputs:
      terraformVersion:
        description: Terraform version
        default: 1.9.0-alpha20240516

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo "variable is ${{vars.TERRAFORM_VERSION_EXP}}"
