name: "Reviewer Assigner"

on:
    pull_request:
    issues:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          script: |