name: "Reviewer Assigner"

on:
    pull_request:
        types: [opened]
    issues:
        types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
                 if (context.eventName == "issues"){
                     try{
                         await github.rest.issues.addAssignees({
                             owner: context.repo.owner,
                             repo: context.repo.repo,
                             assignees: ["BBBmau"], // this will be replaced with pagerduty resp
                             issue_number: context.issue.number, // issue.number is used for both issues and PRs
                         })
                     } catch(error){
                         core.setFailed("error assigning assignee:" + error)
                     }
                 }
                 if (context.eventName == "pull_request"){
                     try{

