name: "Reviewer Assigner"

on:
    pull_request:
        types: [opened]
    issues:
        types: [opened]

jobs:
  assigner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          script: |
                console.log("triggered by: " + context.workflow)

                // if (context.workflow == "issues"){
                //     try{
                //         github.rest.issues.addAssignees({
                //             context.repo.owner,
                //             context.repo.repo,
                //             context.issue.number, // number is based on the workflow_trigger (issue/pull_request number)
                //         })
                //     } catch(error){
                //         core.setFailed("error assigning assignee:" + error)
                //     }
                // }
                // if (context.workflow == "pull_request"){
                //     try{
                //         github.rest.pulls.requestReviewers({
                //             context.repo.owner,
                //             context.repo.repo,
                //             context.issue.number,
                //         })
                //     } catch(error){
                //         core.setFailed("error assigning reviewer:" + error)
                //     }
                // }